version: '3.8'
services:
  # web:
  #   build:
  #     context: ./frontend/spring-vue-teste
  #     dockerfile: Dockerfile
  #     args:
  #         versao: 1.0
  #   ports:
  #     - 8081:80
  #   command: [nginx-debug, '-g', 'daemon off;']

  spring-vue-teste:
    image: vinissaum/spring-vue-teste:1.0
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

